<table width='200' cellspacing='0' cellpadding='0' border='0' style="border: 1px solid #ffffff;">
<tr>
	<td colspan='2' style="text-align: center; font-family: Tahoma, Arial, Sans-serif; font-size: 10pt; font-weight: bold; background-color: #ffffff;">
	Donate to the reunion fund
	</td>
<tr>
<FORM ACTION="https://www.paypal.com/cgi-bin/webscr" METHOD="POST" target="_top">
<INPUT TYPE="hidden" NAME="cmd" VALUE="_xclick">
<INPUT TYPE="hidden" NAME="business" VALUE="aranisate@presnellgage.com">
<INPUT TYPE="hidden" NAME="return" VALUE="http://webott.com/ths">
<INPUT TYPE="hidden" NAME="item_name" VALUE="Troy High School Class of 1991 10-year Reunion Donation">
<INPUT TYPE="hidden" NAME="amount" VALUE="15.00">
	<td width='50%' style="text-align: center; font-family: Tahoma, Arial, Sans-serif; font-size: 8pt;">
	$15 for individuals<br>
<INPUT TYPE="image" SRC="http://images.paypal.com/images/x-click-but04.gif" NAME="submit" ALT="Donate $15.00 for individual">
	</td>
</FORM>
<FORM ACTION="https://www.paypal.com/cgi-bin/webscr" METHOD="POST" target="_top">
<INPUT TYPE="hidden" NAME="cmd" VALUE="_xclick">
<INPUT TYPE="hidden" NAME="business" VALUE="aranisate@presnellgage.com">
<INPUT TYPE="hidden" NAME="return" VALUE="http://webott.com/ths">
<INPUT TYPE="hidden" NAME="item_name" VALUE="Troy High School Class of 1991 10-year Reunion Donation">
<INPUT TYPE="hidden" NAME="amount" VALUE="25.00">
	<td style="text-align: center; font-family: Tahoma, Arial, Sans-serif; font-size: 8pt;">
	$25 for couples<br>
<INPUT TYPE="image" SRC="http://images.paypal.com/images/x-click-but04.gif" NAME="submit" ALT="Donate $25.00 for couple">
	</td>
</FORM>
</table>